AWSTemplateFormatVersion: 2010-09-09
Description: Stack for HEI Admin API

Parameters:
  Env:
    Type: String
  Subnet:
    Type: AWS::EC2::Subnet::Id
  Image:
    Type: String
  ContainerName:
    Type: String
    Default: hei-admin-api
  ContainerPort:
    Type: Number
    Default: 8080
  TasksDesiredCount:
    Type: Number
    Default: 1
  ListenerRuleAvailablePriority:
    Type: Number

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref Env, -hei-admin-api]]
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref Env, -hei-admin-api]]
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: !Join ['', [!Ref Env, -hei-admin-api]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: ENV
              Value: !Ref Env
            - Name: SENTRY_DSN
              Value: !Sub '{{resolve:ssm:/hei-admin-api/sentry/dsn}}'
            - Name: AWS_COGNITO_USERPOOL_ID
              Value: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/cognito/userpool-id}}'
            - Name: AWS_EVENTBRIDGE_BUS
              Value: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/eventbridge/bus-name}}'
            - Name: AWS_SQS_QUEUEURL
              Value: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/sqs/queue-url}}'
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/url}}'
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/password}}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref Env, -hei-admin-api, -ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref Env, -hei-admin-api, -TaskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: hei-admin-api
      DesiredCount: !Ref TasksDesiredCount
      TaskDefinition: !Ref TaskDefinition
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - '{{resolve:ssm:/hei-admin-api/sg:1}}'
          Subnets:
            - !Ref Subnet
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Join ['', [!Ref Env, -ha-api, -TG]]
      Protocol: HTTP
      Port: !Ref ContainerPort
      # TargetType must be ip with Fargate: targets are (de-)registered on container creation/destruction
      TargetType: ip
      #Targets: 
      #  - AvailabilityZone: all
      #    Id: 
      #    Port: ! Ref ContainerPort
      VpcId: '{{resolve:ssm:/hei-admin-api/vpc:1}}'
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 2
      # Spring boot takes up to 70 seconds to start: define UnhealthyThresholdCount*HealthCheckIntervalSecond accordingly
      UnhealthyThresholdCount: 4
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: '{{resolve:ssm:/hei-admin-api/alb-https-listener-arn:1}}'
      Priority: !Ref ListenerRuleAvailablePriority
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Join ['', [api-, !Ref Env, .hei.school]]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
