services:
  db:
    image: postgres:16
    container_name: haapi-local-db
    environment:
      POSTGRES_USER: heiadmin_owner
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: haapidb
    ports:
      - "5433:5432"
    volumes:
      - haapi-db-data:/var/lib/postgresql/data

volumes:
  haapi-db-data: