AWSTemplateFormatVersion: 2010-09-09
Description: Event stack for Hei Admin

Parameters:
  SimpleQueue:
    Type: String
  DLQueue:
    Type: String
  Env:
    Type: String

Resources:
  MailboxQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SimpleQueue
      FifoQueue: false
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
      SqsManagedSseEnabled: false

    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Ref DlQueue
        SqsManagedSseEnabled: false