AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HEI Admin API Spring Boot Application

Parameters:
  Env:
    Type: String
    Default: dev
  Tag:
    Type: String
    Default: latest

Globals:
  Function:
    MemorySize: 1024
    Runtime: java17
    Timeout: 20
    Architectures:
      - x86_64
    Tracing: Active
    VpcConfig:
      SecurityGroupIds:
        - !Sub '{{resolve:ssm:/hei-admin-api/sg}}'
      SubnetIds:
        - !Sub '{{resolve:ssm:/hei-admin-api/public/subnet/id}}'
        - !Sub '{{resolve:ssm:/hei-admin-api/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/hei-admin-api/private/subnet2/id}}'

  Api:
    TracingEnabled: true

Resources:
  HeiAdminApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: school.hei.haapi.LambdaHandler::handleRequest
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          ENV: !Ref Env
          AWS_COGNITO_USERPOOL_ID: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/cognito/userpool-id}}'
          AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/eventbridge/bus-name}}'
          AWS_SQS_QUEUEURL: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/sqs/queue-url}}'
          AWS_SES_SOURCE: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/ses/source}}'
          AWS_SES_CONTACT: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/ses/contact}}'
          SPRING_DATASOURCE_URL: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/url}}'
          SPRING_DATASOURCE_USERNAME: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/username}}'
          SPRING_DATASOURCE_PASSWORD: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/password}}'
          SENTRY_DSN: !Sub '{{resolve:ssm:/hei-admin-api/sentry/dsn}}'
      Events:
        ApiCall:
          Type: Api 
          Properties:
            Path: /{proxy+}
            Method: ANY

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HeiAdminRestApi:
    Description: API Gateway endpoint URL for Prod stage for Hei Admin Api function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  HeiAdminApiFunction:
    Description: Hei Admin Api Lambda Function ARN
    Value: !GetAtt HeiAdminApiFunction.Arn
  HeiAdminApiFunctionIamRole:
    Description: Implicit IAM Role created for Hei Admin Api function
    Value: !GetAtt HeiAdminApiFunctionRole.Arn
