AWSTemplateFormatVersion: "2010-09-09"
Description: haapi - Event

Parameters:
  Env:
    Type: String

Resources:
  MailboxQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['' , [!Ref Env , -1-haapi]]
      VisibilityTimeout: 601 #note(sqs-visibility): WorkerFunction1.Timeout + 1
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue1.Arn
        maxReceiveCount: 5
      SqsManagedSseEnabled: false

  MailboxQueue2:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ '' , [ !Ref Env , -2-haapi ] ]
      VisibilityTimeout: 601 #note(sqs-visibility): WorkerFunction2.Timeout + 1
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue2.Arn
        maxReceiveCount: 5
      SqsManagedSseEnabled: false

  DeadLetterQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:  !Join ['' , [!Ref Env , -1-haapi-dl]]
      SqsManagedSseEnabled: false

  DeadLetterQueue2:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ '' , [ !Ref Env , -2-haapi-dl ] ]
      SqsManagedSseEnabled: false

  MailboxQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MailboxQueue1
        - !Ref MailboxQueue2
      PolicyDocument:
        Version: "2008-10-17"
        Id: "MailboxQueue_Policy"
        Statement:
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue1.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue2.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - Action:
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue1.Arn
            Principal:
              Service:
                - "events.amazonaws.com"
            Condition:
              ArnEquals:
                AWS:SourceArn: !GetAtt EventBridgeRule1.Arn
          - Action:
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue2.Arn
            Principal:
              Service:
                - "events.amazonaws.com"
            Condition:
              ArnEquals:
                AWS:SourceArn: !GetAtt EventBridgeRule2.Arn

  DeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DeadLetterQueue1
        - !Ref DeadLetterQueue2
      PolicyDocument:
        Version: "2008-10-17"
        Id: "DeadLetterQueue_Policy"
        Statement:
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt DeadLetterQueue1.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt DeadLetterQueue2.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

  MailboxQueue1SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/haapi/ , !Ref Env , /1/sqs/mailbox-queue-url]]
      Type: String
      Value: !Ref MailboxQueue1

  MailboxQueue1SSMArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/haapi/ , !Ref Env , /1/sqs/mailbox-queue-arn]]
      Type: String
      Value: !GetAtt MailboxQueue1.Arn

  MailboxQueue2SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '' , [ /haapi/ , !Ref Env , /2/sqs/mailbox-queue-url ] ]
      Type: String
      Value: !Ref MailboxQueue2

  MailboxQueue2SSMArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '' , [ /haapi/ , !Ref Env , /2/sqs/mailbox-queue-arn ] ]
      Type: String
      Value: !GetAtt MailboxQueue2.Arn

  DeadLetterQueue1SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/haapi/ , !Ref Env , /1/sqs/dead-letter-queue-url]]
      Type: String
      Value: !Ref DeadLetterQueue1

  DeadLetterQueue1ArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '' , [ /haapi/ , !Ref Env , /1/sqs/dead-letter-queue-arn ] ]
      Type: String
      Value: !GetAtt DeadLetterQueue1.Arn

  DeadLetterQueue2SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '' , [ /haapi/ , !Ref Env , /2/sqs/dead-letter-queue-url ] ]
      Type: String
      Value: !Ref DeadLetterQueue1

  DeadLetterQueue2ArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '' , [ /haapi/ , !Ref Env , /2/sqs/dead-letter-queue-arn ] ]
      Type: String
      Value: !GetAtt DeadLetterQueue1.Arn

  EventBridgeBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Join ['', [!Ref Env, -haapi]]

  EventBridgeArchive:
    Type: AWS::Events::Archive
    Properties:
      ArchiveName: !Join ['', [!Ref Env, -haapi, -archive]]
      SourceArn: !GetAtt EventBridgeBus.Arn

  EventBridgeRule1:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join ['', [!Ref Env, -1-haapi, -from-api-to-api]]
      EventBusName: !GetAtt EventBridgeBus.Name
      EventPattern:
        source:
          - school.hei.haapi.event1
      Targets:
        - Arn: !GetAtt MailboxQueue1.Arn
          Id: !Join ['', [!Ref Env, -1-haapi, -api-mailbox]]

  EventBridgeRule2:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join [ '', [ !Ref Env, -2-haapi, -from-api-to-api ] ]
      EventBusName: !GetAtt EventBridgeBus.Name
      EventPattern:
        source:
          - school.hei.haapi.event2
      Targets:
        - Arn: !GetAtt MailboxQueue2.Arn
          Id: !Join [ '', [ !Ref Env, -2-haapi, -api-mailbox ] ]

  EventBridgeBusNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['',[/haapi/ , !Ref Env , /eventbridge/bus-name]]
      Type: String
      Value: !GetAtt EventBridgeBus.Name

  EventBridgeBusArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '',[ /haapi/ , !Ref Env , /eventbridge/bus-arn ] ]
      Type: String
      Value: !GetAtt EventBridgeBus.Arn

Outputs:
  MailboxQueue1URL:
    Value: !Ref MailboxQueue1SSM
  MailboxQueue1Arn:
    Value: !Ref MailboxQueue1SSMArn
  DeadLetterQueue1URL:
    Value: !Ref DeadLetterQueue1SSM
  DeadLetterQueue1Arn:
    Value: !Ref DeadLetterQueue1ArnSSM
  MailboxQueue2URL:
    Value: !Ref MailboxQueue2SSM
  MailboxQueue2Arn:
    Value: !Ref MailboxQueue2SSMArn
  DeadLetterQueue2URL:
    Value: !Ref DeadLetterQueue2SSM
  DeadLetterQueue2Arn:
    Value: !Ref DeadLetterQueue2ArnSSM
  EventBridgeBusName:
    Value: !Ref EventBridgeBusNameSSM
  EventBridgeArnName:
    Value: !Ref EventBridgeBusArnSSM
