AWSTemplateFormatVersion: 2010-09-09
Description: haapi - Scheduler

Parameters:
  Env:
    Type: String

Resources:
  LateFeesEmailScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger sendLateFeesEmail function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: LateFeesScheduler
      ScheduleExpression: "cron(0 5 1/2 * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/haapi/${Env}/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.SendLateFeesEmailTriggered'
          Source: 'school.hei.haapi'
  FetchMobileTransactionScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger fetchMobileTransactionTriggered
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: FetchMobileTransactionScheduler
      ScheduleExpression: "cron(0 0 * * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/haapi/${Env}/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.FetchMobileTransactionTriggered'
          Source: 'school.hei.haapi'
  CheckMobilePaymentTransactionScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that check if fee is correctly paid by mobile money
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: CheckMobilePaymentTransactionScheduler
      ScheduleExpression: "cron(0 8 * * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/haapi/${Env}/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.FetchMobileTransactionTriggered'
          Source: 'school.hei.haapi'
  UpdateFeesStatusToLateScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger updateFeesStatusToLate function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: UpdateLateFeesStatusScheduler
      ScheduleExpression: "cron(0 0 * * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/haapi/${Env}/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.UpdateFeesStatusToLateTriggered'
          Source: 'school.hei.haapi'
  CheckAttendanceScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger updateFeesStatusToLate function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: CheckAttendanceScheduler
      ScheduleExpression: "cron(0 */2 ? * MON-SAT *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/haapi/${Env}/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.CheckAttendanceTriggered'
          Source: 'school.hei.haapi'
  UnpaidFeesReminderEmailScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler which triggers sendUnpaidFeesEmail function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: UnpaidFeesReminderEmailScheduler
      ScheduleExpression: "cron(0 8 20 * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/haapi/${Env}/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.SendUnpaidFeesReminderTriggered'
          Source: 'school.hei.haapi'
  ScheduledEventExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ haapi-, !Ref Env, -ScheduledEventExecutionRole ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'