AWSTemplateFormatVersion: '2010-09-09'
Description: Storage stack for HEI Admin API

Parameters:
  Env:
    Type: String
  DBName:
    Type: String
    Default: pgDB
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Join [ '', [ Subnet group for , !Ref Env ] ]
      DBSubnetGroupName: !Join [ '', [ hei-admin-api-, !Ref Env, -subnet-group ] ]
      SubnetIds:
        - !Sub '{{resolve:ssm:/hei-admin-api/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/hei-admin-api/private/subnet2/id}}'

  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/username}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/hei-admin-api/${Env}/db/password}}'
      VPCSecurityGroups: 
        - !Sub '{{resolve:ssm:/hei-admin-api/sg-id}}'
      DBSubnetGroupName: !Ref SubnetGroup
  DatabaseSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /hei-admin-api/, !Ref Env, /db/url ] ]
      Type: String
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - Database
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - Database
                - Endpoint.Port
            - '/'
            - !Ref DBName

Outputs:
  DatabaseSSM:
    Value: !Ref DatabaseSSM
