/*
 * HEI Admin API
 * _Programmatically connect to a computer programming [school](https://hei.school)._ After [joining us](mailto:contact@hei.school), you can get an identification token from our [dev](https://dev-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=5s8cg50doahmu855rlc8fr6qmp&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-dev.hei.school%2Fwhoami) or [prod](https://prod-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=i8bg538jpfu6mqmqb61m26trd&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-prod.hei.school%2Fwhoami) authentication service. Then, start playing with our system!  The implementation of our API is [publicly disclosed](https://github.com/hei-school/hei-admin-api). You are welcome to try and compromise it. Happy hacking! 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package school.hei.haapi.endpoint.rest.api;

import school.hei.haapi.endpoint.rest.client.ApiClient;
import school.hei.haapi.endpoint.rest.client.ApiException;
import school.hei.haapi.endpoint.rest.client.ApiResponse;
import school.hei.haapi.endpoint.rest.client.Pair;

import school.hei.haapi.endpoint.rest.model.BadRequestException;
import school.hei.haapi.endpoint.rest.model.Course;
import school.hei.haapi.endpoint.rest.model.CourseDirection;
import school.hei.haapi.endpoint.rest.model.CrupdateCourse;
import school.hei.haapi.endpoint.rest.model.ExamDetail;
import school.hei.haapi.endpoint.rest.model.ExamInfo;
import school.hei.haapi.endpoint.rest.model.Group;
import school.hei.haapi.endpoint.rest.model.InternalServerException;
import school.hei.haapi.endpoint.rest.model.NotAuthorizedException;
import school.hei.haapi.endpoint.rest.model.ResourceNotFoundException;
import school.hei.haapi.endpoint.rest.model.StudentCourseExam;
import school.hei.haapi.endpoint.rest.model.StudentGrade;
import school.hei.haapi.endpoint.rest.model.TooManyRequestsException;
import school.hei.haapi.endpoint.rest.model.UpdateStudentGrade;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.function.Consumer;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;

@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-07T21:29:18.718768+01:00[Europe/Paris]")
public class TeachingApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public TeachingApi() {
    this(new ApiClient());
  }

  public TeachingApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new groups or update existing groups
   * Update groups when &#x60;id&#x60; are provided, create them otherwise.
   * @param group Groups to update (required)
   * @return List&lt;Group&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Group> createOrUpdateGroups(List<Group> group) throws ApiException {
    ApiResponse<List<Group>> localVarResponse = createOrUpdateGroupsWithHttpInfo(group);
    return localVarResponse.getData();
  }

  /**
   * Create new groups or update existing groups
   * Update groups when &#x60;id&#x60; are provided, create them otherwise.
   * @param group Groups to update (required)
   * @return ApiResponse&lt;List&lt;Group&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Group>> createOrUpdateGroupsWithHttpInfo(List<Group> group) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createOrUpdateGroupsRequestBuilder(group);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("createOrUpdateGroups", localVarResponse);
      }
      return new ApiResponse<List<Group>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Group>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createOrUpdateGroupsRequestBuilder(List<Group> group) throws ApiException {
    // verify the required parameter 'group' is set
    if (group == null) {
      throw new ApiException(400, "Missing the required parameter 'group' when calling createOrUpdateGroups");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/groups";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(group);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Crupdate courses
   * Update courses when id are provided, create them otherwise.
   * @param crupdateCourse  (required)
   * @return List&lt;Course&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Course> crupdateCourses(List<CrupdateCourse> crupdateCourse) throws ApiException {
    ApiResponse<List<Course>> localVarResponse = crupdateCoursesWithHttpInfo(crupdateCourse);
    return localVarResponse.getData();
  }

  /**
   * Crupdate courses
   * Update courses when id are provided, create them otherwise.
   * @param crupdateCourse  (required)
   * @return ApiResponse&lt;List&lt;Course&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Course>> crupdateCoursesWithHttpInfo(List<CrupdateCourse> crupdateCourse) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateCoursesRequestBuilder(crupdateCourse);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("crupdateCourses", localVarResponse);
      }
      return new ApiResponse<List<Course>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Course>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateCoursesRequestBuilder(List<CrupdateCourse> crupdateCourse) throws ApiException {
    // verify the required parameter 'crupdateCourse' is set
    if (crupdateCourse == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateCourse' when calling crupdateCourses");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateCourse);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Update exams if ID is provided, otherwise create new exams of the specified course.
   * 
   * @param courseId  (required)
   * @param examInfo  (required)
   * @return List&lt;ExamInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public List<ExamInfo> crupdateExams(String courseId, List<ExamInfo> examInfo) throws ApiException {
    ApiResponse<List<ExamInfo>> localVarResponse = crupdateExamsWithHttpInfo(courseId, examInfo);
    return localVarResponse.getData();
  }

  /**
   * Update exams if ID is provided, otherwise create new exams of the specified course.
   * 
   * @param courseId  (required)
   * @param examInfo  (required)
   * @return ApiResponse&lt;List&lt;ExamInfo&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<ExamInfo>> crupdateExamsWithHttpInfo(String courseId, List<ExamInfo> examInfo) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateExamsRequestBuilder(courseId, examInfo);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("crupdateExams", localVarResponse);
      }
      return new ApiResponse<List<ExamInfo>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<ExamInfo>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateExamsRequestBuilder(String courseId, List<ExamInfo> examInfo) throws ApiException {
    // verify the required parameter 'courseId' is set
    if (courseId == null) {
      throw new ApiException(400, "Missing the required parameter 'courseId' when calling crupdateExams");
    }
    // verify the required parameter 'examInfo' is set
    if (examInfo == null) {
      throw new ApiException(400, "Missing the required parameter 'examInfo' when calling crupdateExams");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{course_id}/exams"
        .replace("{course_id}", ApiClient.urlEncode(courseId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(examInfo);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Update students grades
   * 
   * @param courseId  (required)
   * @param examId  (required)
   * @param updateStudentGrade  (required)
   * @return ExamDetail
   * @throws ApiException if fails to make API call
   */
  public ExamDetail crupdateStudentsGrade(String courseId, String examId, List<UpdateStudentGrade> updateStudentGrade) throws ApiException {
    ApiResponse<ExamDetail> localVarResponse = crupdateStudentsGradeWithHttpInfo(courseId, examId, updateStudentGrade);
    return localVarResponse.getData();
  }

  /**
   * Update students grades
   * 
   * @param courseId  (required)
   * @param examId  (required)
   * @param updateStudentGrade  (required)
   * @return ApiResponse&lt;ExamDetail&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ExamDetail> crupdateStudentsGradeWithHttpInfo(String courseId, String examId, List<UpdateStudentGrade> updateStudentGrade) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateStudentsGradeRequestBuilder(courseId, examId, updateStudentGrade);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("crupdateStudentsGrade", localVarResponse);
      }
      return new ApiResponse<ExamDetail>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ExamDetail>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateStudentsGradeRequestBuilder(String courseId, String examId, List<UpdateStudentGrade> updateStudentGrade) throws ApiException {
    // verify the required parameter 'courseId' is set
    if (courseId == null) {
      throw new ApiException(400, "Missing the required parameter 'courseId' when calling crupdateStudentsGrade");
    }
    // verify the required parameter 'examId' is set
    if (examId == null) {
      throw new ApiException(400, "Missing the required parameter 'examId' when calling crupdateStudentsGrade");
    }
    // verify the required parameter 'updateStudentGrade' is set
    if (updateStudentGrade == null) {
      throw new ApiException(400, "Missing the required parameter 'updateStudentGrade' when calling crupdateStudentsGrade");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{course_id}/exams/{exam_id}/grades"
        .replace("{course_id}", ApiClient.urlEncode(courseId.toString()))
        .replace("{exam_id}", ApiClient.urlEncode(examId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateStudentGrade);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get course by identifier
   * 
   * @param id  (required)
   * @return Course
   * @throws ApiException if fails to make API call
   */
  public Course getCourseById(String id) throws ApiException {
    ApiResponse<Course> localVarResponse = getCourseByIdWithHttpInfo(id);
    return localVarResponse.getData();
  }

  /**
   * Get course by identifier
   * 
   * @param id  (required)
   * @return ApiResponse&lt;Course&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Course> getCourseByIdWithHttpInfo(String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCourseByIdRequestBuilder(id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getCourseById", localVarResponse);
      }
      return new ApiResponse<Course>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Course>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCourseByIdRequestBuilder(String id) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCourseById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get all courses
   * 
   * @param code Filter courses by code, case is ignored (optional)
   * @param name Filter courses by name, case is ignored (optional)
   * @param credits Filter courses by credits (optional)
   * @param teacherFirstName Filter courses by teacher firstname, case is ignored (optional)
   * @param teacherLastName Filter courses by teacher lastname, case is ignored (optional)
   * @param creditsOrder  (optional)
   * @param codeOrder  (optional)
   * @param page Set value to 1 by default if null is provided (optional)
   * @param pageSize Set value to 15 by default if null is provided (optional)
   * @return List&lt;Course&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Course> getCourses(String code, String name, Integer credits, String teacherFirstName, String teacherLastName, CourseDirection creditsOrder, CourseDirection codeOrder, Integer page, Integer pageSize) throws ApiException {
    ApiResponse<List<Course>> localVarResponse = getCoursesWithHttpInfo(code, name, credits, teacherFirstName, teacherLastName, creditsOrder, codeOrder, page, pageSize);
    return localVarResponse.getData();
  }

  /**
   * Get all courses
   * 
   * @param code Filter courses by code, case is ignored (optional)
   * @param name Filter courses by name, case is ignored (optional)
   * @param credits Filter courses by credits (optional)
   * @param teacherFirstName Filter courses by teacher firstname, case is ignored (optional)
   * @param teacherLastName Filter courses by teacher lastname, case is ignored (optional)
   * @param creditsOrder  (optional)
   * @param codeOrder  (optional)
   * @param page Set value to 1 by default if null is provided (optional)
   * @param pageSize Set value to 15 by default if null is provided (optional)
   * @return ApiResponse&lt;List&lt;Course&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Course>> getCoursesWithHttpInfo(String code, String name, Integer credits, String teacherFirstName, String teacherLastName, CourseDirection creditsOrder, CourseDirection codeOrder, Integer page, Integer pageSize) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCoursesRequestBuilder(code, name, credits, teacherFirstName, teacherLastName, creditsOrder, codeOrder, page, pageSize);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getCourses", localVarResponse);
      }
      return new ApiResponse<List<Course>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Course>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCoursesRequestBuilder(String code, String name, Integer credits, String teacherFirstName, String teacherLastName, CourseDirection creditsOrder, CourseDirection codeOrder, Integer page, Integer pageSize) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses";

    List<Pair> localVarQueryParams = new ArrayList<>();
    localVarQueryParams.addAll(ApiClient.parameterToPairs("code", code));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("name", name));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("credits", credits));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("teacher_first_name", teacherFirstName));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("teacher_last_name", teacherLastName));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("credits_order", creditsOrder));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("code_order", codeOrder));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));

    if (!localVarQueryParams.isEmpty()) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get exam details with the participants and their grades of the specified exam.
   * 
   * @param courseId  (required)
   * @param examId  (required)
   * @return ExamDetail
   * @throws ApiException if fails to make API call
   */
  public ExamDetail getExamDetail(String courseId, String examId) throws ApiException {
    ApiResponse<ExamDetail> localVarResponse = getExamDetailWithHttpInfo(courseId, examId);
    return localVarResponse.getData();
  }

  /**
   * Get exam details with the participants and their grades of the specified exam.
   * 
   * @param courseId  (required)
   * @param examId  (required)
   * @return ApiResponse&lt;ExamDetail&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ExamDetail> getExamDetailWithHttpInfo(String courseId, String examId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getExamDetailRequestBuilder(courseId, examId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getExamDetail", localVarResponse);
      }
      return new ApiResponse<ExamDetail>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ExamDetail>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getExamDetailRequestBuilder(String courseId, String examId) throws ApiException {
    // verify the required parameter 'courseId' is set
    if (courseId == null) {
      throw new ApiException(400, "Missing the required parameter 'courseId' when calling getExamDetail");
    }
    // verify the required parameter 'examId' is set
    if (examId == null) {
      throw new ApiException(400, "Missing the required parameter 'examId' when calling getExamDetail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{course_id}/exams/{exam_id}/details"
        .replace("{course_id}", ApiClient.urlEncode(courseId.toString()))
        .replace("{exam_id}", ApiClient.urlEncode(examId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get all exam infos of a specified course
   * 
   * @param courseId  (required)
   * @return List&lt;ExamInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public List<ExamInfo> getExamsByCourseId(String courseId) throws ApiException {
    ApiResponse<List<ExamInfo>> localVarResponse = getExamsByCourseIdWithHttpInfo(courseId);
    return localVarResponse.getData();
  }

  /**
   * Get all exam infos of a specified course
   * 
   * @param courseId  (required)
   * @return ApiResponse&lt;List&lt;ExamInfo&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<ExamInfo>> getExamsByCourseIdWithHttpInfo(String courseId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getExamsByCourseIdRequestBuilder(courseId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getExamsByCourseId", localVarResponse);
      }
      return new ApiResponse<List<ExamInfo>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<ExamInfo>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getExamsByCourseIdRequestBuilder(String courseId) throws ApiException {
    // verify the required parameter 'courseId' is set
    if (courseId == null) {
      throw new ApiException(400, "Missing the required parameter 'courseId' when calling getExamsByCourseId");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{course_id}/exams"
        .replace("{course_id}", ApiClient.urlEncode(courseId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get group by identifier
   * 
   * @param id  (required)
   * @return Group
   * @throws ApiException if fails to make API call
   */
  public Group getGroupById(String id) throws ApiException {
    ApiResponse<Group> localVarResponse = getGroupByIdWithHttpInfo(id);
    return localVarResponse.getData();
  }

  /**
   * Get group by identifier
   * 
   * @param id  (required)
   * @return ApiResponse&lt;Group&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Group> getGroupByIdWithHttpInfo(String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getGroupByIdRequestBuilder(id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getGroupById", localVarResponse);
      }
      return new ApiResponse<Group>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Group>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getGroupByIdRequestBuilder(String id) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getGroupById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/groups/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get all groups
   * 
   * @return List&lt;Group&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Group> getGroups() throws ApiException {
    ApiResponse<List<Group>> localVarResponse = getGroupsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get all groups
   * 
   * @return ApiResponse&lt;List&lt;Group&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Group>> getGroupsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getGroupsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getGroups", localVarResponse);
      }
      return new ApiResponse<List<Group>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Group>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getGroupsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/groups";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Return a participant with his grade for the specified exam
   * 
   * @param courseId  (required)
   * @param examId  (required)
   * @param participantId  (required)
   * @return StudentGrade
   * @throws ApiException if fails to make API call
   */
  public StudentGrade getParticipantById(String courseId, String examId, String participantId) throws ApiException {
    ApiResponse<StudentGrade> localVarResponse = getParticipantByIdWithHttpInfo(courseId, examId, participantId);
    return localVarResponse.getData();
  }

  /**
   * Return a participant with his grade for the specified exam
   * 
   * @param courseId  (required)
   * @param examId  (required)
   * @param participantId  (required)
   * @return ApiResponse&lt;StudentGrade&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<StudentGrade> getParticipantByIdWithHttpInfo(String courseId, String examId, String participantId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getParticipantByIdRequestBuilder(courseId, examId, participantId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getParticipantById", localVarResponse);
      }
      return new ApiResponse<StudentGrade>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<StudentGrade>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getParticipantByIdRequestBuilder(String courseId, String examId, String participantId) throws ApiException {
    // verify the required parameter 'courseId' is set
    if (courseId == null) {
      throw new ApiException(400, "Missing the required parameter 'courseId' when calling getParticipantById");
    }
    // verify the required parameter 'examId' is set
    if (examId == null) {
      throw new ApiException(400, "Missing the required parameter 'examId' when calling getParticipantById");
    }
    // verify the required parameter 'participantId' is set
    if (participantId == null) {
      throw new ApiException(400, "Missing the required parameter 'participantId' when calling getParticipantById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{course_id}/exams/{exam_id}/participants/{participant_id}"
        .replace("{course_id}", ApiClient.urlEncode(courseId.toString()))
        .replace("{exam_id}", ApiClient.urlEncode(examId.toString()))
        .replace("{participant_id}", ApiClient.urlEncode(participantId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get all grades of a student in every course that had an exam.
   * 
   * @param studentId  (required)
   * @return List&lt;StudentCourseExam&gt;
   * @throws ApiException if fails to make API call
   */
  public List<StudentCourseExam> getStudentGrades(String studentId) throws ApiException {
    ApiResponse<List<StudentCourseExam>> localVarResponse = getStudentGradesWithHttpInfo(studentId);
    return localVarResponse.getData();
  }

  /**
   * Get all grades of a student in every course that had an exam.
   * 
   * @param studentId  (required)
   * @return ApiResponse&lt;List&lt;StudentCourseExam&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<StudentCourseExam>> getStudentGradesWithHttpInfo(String studentId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getStudentGradesRequestBuilder(studentId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      if (localVarResponse.statusCode()/ 100 != 2) {
        throw getApiException("getStudentGrades", localVarResponse);
      }
      return new ApiResponse<List<StudentCourseExam>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<StudentCourseExam>>() {})
        );
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getStudentGradesRequestBuilder(String studentId) throws ApiException {
    // verify the required parameter 'studentId' is set
    if (studentId == null) {
      throw new ApiException(400, "Missing the required parameter 'studentId' when calling getStudentGrades");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/students/{student_id}/grades"
        .replace("{student_id}", ApiClient.urlEncode(studentId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
