ALTER TABLE "user" ALTER COLUMN sex DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN address DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN birth_date DROP NOT NULL;