name: CD event

on:
  push:
    branches:
      - 'dev'
      - 'prod'
      - 'preprod'

  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure dev AWS credentials
        if: ${{ github.ref_name == 'dev' }}
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure prod AWS credentials
        if: ${{ github.ref_name == 'prod' }}
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Put branch_env into GITHUB_ENV
        run: echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-event-hei-admin-api
          template: cf-stacks/event-stack.yml
          tags: "[ { \"Key\": \"App\", \"Value\": \"hei-admin\" }, { \"Key\": \"Env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ env.branch_env }}"