name: CD storage database

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:

jobs:
  cd-storage:
    if: github.ref_name == 'prod' || github.ref_name == 'preprod'

    runs-on: ubuntu-latest

    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - name: Deploy storage database stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          # TODO: -storage- --> -database-. But it will BREAK backward compatibility.
          name: ${{ github.ref_name }}-storage-haapi
          template: cf-stacks/storage-database-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"haapi\" }, { \"Key\": \"env\", \"Value\": \"${{ github.ref_name }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ github.ref_name }},
            ProdDbClusterTimeout=${{ vars.PROD_DB_CLUSTER_TIMEOUT }}"
