name: Sched Del compute

on:
  schedule:
    - cron: '59 20 * * 1,2,3,4,5'

  workflow_dispatch:

jobs:
  delete_compute_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ''
          workdir: ''

      - name: Connect to AWS
        run: sh ./.shell/initAWS.sh ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }} ${{ secrets.DEV_AWS_REGION }}

      - name: Put branch_env into GITHUB_ENV
        run: echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: delete compute stack
        run: aws cloudformation delete-stack --stack-name ${{ env.branch_env }}-compute-hei-admin-api